export const baseURL = "https://roverebike.ca/";

export const additionalPrices = {
  shipping: 100, // Default shipping price CAD
  tax: 30, // Percentage of the total amount
};
export const cities = {
  canada: {
    shipping: 0,
    items: [
      {
        name: "Alberta",
        taxPercantage: 5,
        cities: [
          "Acton Vale",
          "Adstock",
          "Akwesasne",
          "Albanel",
          "Alma",
          "Amherst",
          "Amos",
          "Amqui",
          "Amulet",
          "Asbestos",
          "Ascot Corner",
          "Austin",
          "Ayer’s Cliff",
          "Baie-Comeau",
          "Baie-du-Febvre",
          "Baie-d’Urfé",
          "Baie-Saint-Paul",
          "Barraute",
          "Beaconsfield",
          "Beauceville",
          "Beauharnois",
          "Beauport",
          "Beaupré",
          "Bécancour",
          "Bedford",
          "Beloeil",
          "Berthier-sur-Mer",
          "Berthierville",
          "Blainville",
          "Blanc-Sablon",
          "Bois-des-Filion",
          "Boisbriand",
          "Boischatel",
          "Bonaventure",
          "Boucherville",
          "Brébeuf",
          "Brigham",
          "Bristol",
          "Bromont",
          "Brossard",
          "Brownsburg",
          "Bury",
          "Candiac",
          "Cantley",
          "Cap Santé",
          "Cap-Chat",
          "Cap-Saint-Ignace",
          "Caplan",
          "Carignan",
          "Carleton-sur-Mer",
          "Causapscal",
          "Chambly",
          "Chambord",
          "Champlain",
          "Chandler",
          "Chapais",
          "Charlemagne",
          "Château-Richer",
          "Châteauguay",
          "Chertsey",
          "Chibougamau",
          "Chisasibi",
          "Chute-aux-Outardes",
          "Clarendon",
          "Clermont",
          "Cleveland",
          "Coaticook",
          "Coleraine",
          "Compton",
          "Contrecoeur",
          "Cookshire",
          "Côte-Saint-Luc",
          "Coteau-du-Lac",
          "Cowansville",
          "Crabtree",
          "Danville",
          "Dégelis",
          "Déléage",
          "Delson",
          "Desbiens",
          "Deschambault",
          "Deux-Montagnes",
          "Disraeli",
          "Dollard-des-Ormeaux",
          "Donnacona",
          "Dorval",
          "Drummondville",
          "Dudswell",
          "Dunham",
          "Durham-Sud",
          "East Angus",
          "East Broughton",
          "Eastman",
          "Eeyou Istchee Baie-James",
          "Farnham",
          "Ferme-Neuve",
          "Fermont",
          "Forestville",
          "Fort-Coulonge",
          "Fossambault-sur-le-Lac",
          "Frampton",
          "Franklin Centre",
          "Frelighsburg",
          "Frontenac",
          "Gaspé",
          "Gatineau",
          "Girardville",
          "Godmanchester",
          "Gore",
          "Gracefield",
          "Granby",
          "Grand-Remous",
          "Grande-Rivière",
          "Grande-Vallée",
          "Grenville",
          "Grenville-sur-la-Rouge",
          "Hampstead",
        ],
      },
      {
        name: "British Columbia",
        taxPercantage: 5,
        cities: [
          "Abbotsford",
          "Anmore",
          "Armstrong",
          "Ashcroft",
          "Barrière",
          "Bowen Island",
          "Burnaby",
          "Burns Lake",
          "Campbell River",
          "Castlegar",
          "Cedar",
          "Central Saanich",
          "Chase",
          "Chetwynd",
          "Chilliwack",
          "Clearwater",
          "Coldstream",
          "Colwood",
          "Comox",
          "Coombs",
          "Coquitlam",
          "Courtenay",
          "Cowichan Bay",
          "Cranbrook",
          "Creston",
          "Cumberland",
          "Dawson Creek",
          "Delta",
          "Duncan",
          "Dunsmuir",
          "East Kelowna",
          "Elkford",
          "Ellison",
          "Enderby",
          "Errington",
          "Esquimalt",
          "Fernie",
          "Fort St. James",
          "Fort St. John",
          "Fruitvale",
          "Gibsons",
          "Gold River",
          "Golden",
          "Grand Forks",
          "Grindrod",
          "Harrison Hot Springs",
          "Highlands",
          "Hilliers",
          "Hope",
          "Houston",
          "Hudson Hope",
          "Invermere",
          "Kaleden",
          "Kamloops",
          "Kelowna",
          "Kent",
          "Keremeos",
          "Kimberley",
          "Kitimat",
          "Ladysmith",
          "Lake Country",
          "Lake Cowichan",
          "Lakeview",
          "Langford Station",
          "Langley",
          "Lillooet",
          "Lions Bay",
          "Logan Lake",
          "Lumby",
          "Mackenzie",
          "Maple Ridge",
          "Merritt",
          "Metchosin",
          "Mission",
          "Nakusp",
          "Nanaimo",
          "Naramata",
          "Nelson",
          "New Westminster",
          "Nisga'a",
          "North Cowichan",
          "North Saanich",
          "North Vancouver",
          "Northern Rockies",
          "Oak Bay",
          "Oliver",
          "One Hundred Mile House",
          "Ootischenia",
          "Osoyoos",
          "Parksville",
          "Peachland",
          "Pemberton",
          "Penticton",
          "Pitt Meadows",
          "Popkum",
          "Port Alberni",
          "Port Coquitlam",
          "Port Hardy",
          "Port McNeill",
          "Port Moody",
          "Powell River",
          "Prince George",
          "Prince Rupert",
          "Princeton",
          "Qualicum Beach",
          "Quesnel",
          "Richmond",
          "Rossland",
          "Royston",
          "Saanich",
          "Salmo",
          "Salmon Arm",
          "Saltair",
          "Sechelt",
          "Sicamous",
          "Sidney",
          "Smithers",
          "Sooke",
          "Sorrento",
          "Spallumcheen",
          "Sparwood",
          "Squamish",
          "Summerland",
          "Surrey",
          "Taylor",
          "Telkwa",
          "Terrace",
          "Tofino",
          "Trail",
          "Tumbler Ridge",
          "Ucluelet",
          "Valemount",
          "Vancouver",
          "Vanderhoof",
          "Vernon",
          "Victoria",
          "View Royal",
          "Warfield",
          "West Vancouver",
          "Westbank",
          "Whistler",
          "White Rock",
          "Williams Lake",
          "Windermere",
          "Youbou",
        ],
      },
      {
        name: "Manitoba",
        taxPercantage: 5,
        cities: [
          "Alexander",
          "Alonsa",
          "Altona",
          "Arborg",
          "Argyle",
          "Armstrong",
          "Beauséjour",
          "Bifrost-Riverton",
          "Blumenort",
          "Boissevain",
          "Brandon",
          "Brenda-Waskada",
          "Brokenhead",
          "Carberry",
          "Carman",
          "Cartier",
          "Cartwright-Roblin",
          "Clanwilliam-Erickson",
          "Coldwell",
          "Cornwallis",
          "Dauphin",
          "De Salaberry",
          "Deloraine-Winchester",
          "Dufferin",
          "East St. Paul",
          "Ellice-Archie",
          "Elton",
          "Emerson-Franklin",
          "Ethelbert",
          "Fisher",
          "Flin Flon (Part)",
          "Gilbert Plains",
          "Gillam",
          "Gimli",
          "Glenboro-South Cypress",
          "Glenella-Lansdowne",
          "Grahamdale",
          "Grand View",
          "Grassland",
          "Grey",
          "Grunthal",
          "Hamiota",
          "Hanover",
          "Harrison Park",
          "Headingley",
          "Hillsburg-Roblin-Shell River",
          "Kelsey",
          "Killarney - Turtle Mountain",
          "La Broquerie",
          "Lac du Bonnet",
          "Lakeshore",
          "Landmark",
          "Lorette",
          "Lorne",
          "Louise",
          "Macdonald",
          "McCreary",
          "Melita",
          "Minitonas-Bowsman",
          "Minnedosa",
          "Minto-Odanah",
          "Mitchell",
          "Montcalm",
          "Morden",
          "Morris",
          "Mossey River",
          "Neepawa",
          "Niverville",
          "Norfolk-Treherne",
          "North Cypress-Langford",
          "North Norfolk",
          "Oakland-Wawanesa",
          "Oakview",
          "Pembina",
          "Pinawa",
          "Piney",
          "Pipestone",
          "Portage La Prairie",
          "Powerview-Pine Falls",
          "Prairie Lakes",
          "Prairie View",
          "Reinland",
          "Reynolds",
          "Riding Mountain West",
          "Ritchot",
          "Riverdale",
          "Rockwood",
          "Roland",
          "Rosedale",
          "Rossburn",
          "Rosser",
          "Russell-Binscarth",
          "Selkirk",
          "Sifton",
          "Souris-Glenwood",
          "Springfield",
          "St-Pierre-Jolys",
          "St. Andrews",
          "St. Clements",
          "St. François Xavier",
          "St. Laurent",
          "Stanley",
          "Ste. Anne",
          "Ste. Rose",
          "Steinbach",
          "Stonewall",
          "Stuartburn",
          "Swan River",
          "Swan Valley West",
          "Taché",
          "Teulon",
          "The Pas",
          "Thompson",
          "Two Borders",
          "Victoria",
          "Virden",
          "Wallace-Woodworth",
          "Wasagamack",
          "West Interlake",
          "West St. Paul",
          "WestLake-Gladstone",
          "Whitehead",
          "Winkler",
          "Winnipeg",
          "Winnipeg Beach",
          "Woodlands",
          "Yellowhead",
        ],
      },
      {
        name: "Northwest Territories",
        taxPercantage: 5,
        cities: [
          "Behchokò",
          "Fort Simpson",
          "Fort Smith",
          "Hay River",
          "Inuvik",
          "Yellowknife",
        ],
      },
      {
        name: "Nunavut",
        taxPercantage: 5,
        cities: [
          "Arviat",
          "Baker Lake",
          "Cambridge Bay",
          "Cape Dorset",
          "Clyde River",
          "Gjoa Haven",
          "Igloolik",
          "Iqaluit",
          "Kugluktuk",
          "Pangnirtung",
          "Pond Inlet",
          "Rankin Inlet",
          "Repulse Bay",
          "Taloyoak",
        ],
      },
      {
        name: "Quebec",
        taxPercantage: 5,
        cities: [
          "Acton Vale",
          "Adstock",
          "Akwesasne",
          "Albanel",
          "Alma",
          "Amherst",
          "Amos",
          "Amqui",
          "Amulet",
          "Asbestos",
          "Ascot Corner",
          "Austin",
          "Ayer’s Cliff",
          "Baie-Comeau",
          "Baie-du-Febvre",
          "Baie-d’Urfé",
          "Baie-Saint-Paul",
          "Barraute",
          "Beaconsfield",
          "Beauceville",
          "Beauharnois",
          "Beauport",
          "Beaupré",
          "Bécancour",
          "Bedford",
          "Beloeil",
          "Berthier-sur-Mer",
          "Berthierville",
          "Blainville",
          "Blanc-Sablon",
          "Bois-des-Filion",
          "Boisbriand",
          "Boischatel",
          "Bonaventure",
          "Boucherville",
          "Brébeuf",
          "Brigham",
          "Bristol",
          "Bromont",
          "Brossard",
          "Brownsburg",
          "Bury",
          "Candiac",
          "Cantley",
          "Cap Santé",
          "Cap-Chat",
          "Cap-Saint-Ignace",
          "Caplan",
          "Carignan",
          "Carleton-sur-Mer",
          "Causapscal",
          "Chambly",
          "Chambord",
          "Champlain",
          "Chandler",
          "Chapais",
          "Charlemagne",
          "Château-Richer",
          "Châteauguay",
          "Chertsey",
          "Chibougamau",
          "Chisasibi",
          "Chute-aux-Outardes",
          "Clarendon",
          "Clermont",
          "Cleveland",
          "Coaticook",
          "Coleraine",
          "Compton",
          "Contrecoeur",
          "Cookshire",
          "Côte-Saint-Luc",
          "Coteau-du-Lac",
          "Cowansville",
          "Crabtree",
          "Danville",
          "Dégelis",
          "Déléage",
          "Delson",
          "Desbiens",
          "Deschambault",
          "Deux-Montagnes",
          "Disraeli",
          "Dollard-des-Ormeaux",
          "Donnacona",
          "Dorval",
          "Drummondville",
          "Dudswell",
          "Dunham",
          "Durham-Sud",
          "East Angus",
          "East Broughton",
          "Eastman",
          "Eeyou Istchee Baie-James",
          "Farnham",
          "Ferme-Neuve",
          "Fermont",
          "Forestville",
          "Fort-Coulonge",
          "Fossambault-sur-le-Lac",
          "Frampton",
          "Franklin Centre",
          "Frelighsburg",
          "Frontenac",
          "Gaspé",
          "Gatineau",
          "Girardville",
          "Godmanchester",
          "Gore",
          "Gracefield",
          "Granby",
          "Grand-Remous",
          "Grande-Rivière",
          "Grande-Vallée",
          "Grenville",
          "Grenville-sur-la-Rouge",
          "Hampstead",
          "Hatley",
          "Havre-Saint-Pierre",
          "Hébertville",
          "Hemmingford",
          "Henryville",
          "Hérbertville",
          "Hérouxville",
          "Hinchinbrooke",
          "Hudson",
          "Huntingdon",
          "Inukjuak",
          "Joliette",
          "Kingsey Falls",
          "Kirkland",
          "Kuujjuaq",
          "L'Ange-Gardien",
          "L'Anse-Saint-Jean",
          "L'Ascension-de-Notre-Seigneur",
          "L'Isle-aux-Allumettes",
          "L'Isle-aux-Coudres",
          "La Conception",
          "La Doré",
          "La Guadeloupe",
          "La Macaza",
          "La Malbaie",
          "La Minerve",
          "La Pêche",
          "La Pocatière",
          "La Prairie",
          "La Présentation",
          "La Sarre",
          "La Tuque",
          "Labelle",
          "Labrecque",
          "Lac-au-Saumon",
          "Lac-aux-Sables",
          "Lac-Bouchette",
          "Lac-Brome",
          "Lac-des-Écorces",
          "Lac-Drolet",
          "Lac-Etchemin",
          "Lac-Mégantic",
          "Lac-Nominingue",
          "Lac-Supérieur",
          "Lachute",
          "Lacolle",
          "Lambton",
          "Lanoraie",
          "Larouche",
          "Laurier-Station",
          "Laurierville",
          "Laval",
          "Lavaltrie",
          "Lebel-sur-Quévillon",
          "Léry",
          "Les Cèdres",
          "Les Coteaux",
          "Les Éboulements",
          "Les Escoumins",
          "Les Îles-de-la-Madeleine",
          "Les Méchins",
          "Lévis",
          "Listuguj",
          "Longue-Rive",
          "Longueuil",
          "Lorraine",
          "Lorrainville",
          "Louiseville",
          "Lyster",
          "L’ Îsle-Verte",
          "L’Ancienne-Lorette",
          "L’Assomption",
          "L’Avenir",
          "L’Epiphanie",
          "L’Île-Perrot",
          "L’Islet-sur-Mer",
          "Macamic",
          "Magog",
          "Malartic",
          "Maliotenam",
          "Mandeville",
          "Maniwaki",
          "Manouane",
          "Mansfield-et-Pontefract",
          "Maria",
          "Marieville",
          "Mascouche",
          "Mashteuiatsh",
          "Maskinongé",
          "Matagami",
          "Matane",
          "McMasterville",
          "Melbourne",
          "Mercier",
          "Messines",
          "Métabetchouan-Lac-à-la-Croix",
          "Mille-Isles",
          "Mirabel",
          "Mistassini",
          "Mistissini",
          "Mont-Carmel",
          "Mont-Joli",
          "Mont-Laurier",
          "Mont-Orford",
          "Mont-Royal",
          "Mont-Saint-Grégoire",
          "Mont-Saint-Hilaire",
          "Mont-Tremblant",
          "Montmagny",
          "Montréal",
          "Montréal-Est",
          "Montréal-Ouest",
          "Morin-Heights",
          "Nantes",
          "Napierville",
          "Neuville",
          "New Carlisle",
          "New Richmond",
          "Nicolet",
          "Normandin",
          "Notre-Dame-de-l'Île-Perrot",
          "Notre-Dame-de-Lourdes",
          "Notre-Dame-des-Neiges",
          "Notre-Dame-des-Pins",
          "Notre-Dame-des-Prairies",
          "Notre-Dame-du-Bon-Conseil",
          "Notre-Dame-du-Laus",
          "Notre-Dame-du-Mont-Carmel",
          "Notre-Dame-du-Nord",
          "Notre-Dame-du-Portage",
          "Nouvelle",
          "Noyan",
          "Obedjiwan",
          "Oka",
          "Old Chelsea",
          "Ormstown",
          "Otterburn Park",
          "Palmarolle",
          "Papineauville",
          "Paspebiac",
          "Percé",
          "Pessamit",
          "Piedmont",
          "Pierreville",
          "Pincourt",
          "Plaisance",
          "Plessisville",
          "Pohénégamook",
          "Pointe-à-la-Croix",
          "Pointe-aux-Outardes",
          "Pointe-Calumet",
          "Pointe-Claire",
          "Pointe-des-Cascades",
          "Pointe-Lebel",
          "Pont-Rouge",
          "Pontiac",
          "Port-Cartier",
          "Port-Daniel--Gascons",
          "Portneuf",
          "Potton",
          "Povungnituk",
          "Prévost",
          "Price",
          "Princeville",
          "Quebec City",
          "Racine",
          "Ragueneau",
          "Rawdon",
          "Repentigny",
          "Richelieu",
          "Richmond",
          "Rigaud",
          "Rimouski",
          "Ripon",
          "Rivière-Beaudette",
          "Rivière-Blanche",
          "Rivière-Bleue",
          "Rivière-du-Loup",
          "Rivière-Héva",
          "Riviere-Ouelle",
          "Rivière-Rouge",
          "Roberval",
          "Rosemère",
          "Rougemont",
          "Rouyn-Noranda",
          "Roxton Falls",
          "Roxton Pond",
          "Roxton-Sud",
          "Sacré-Coeur-Saguenay",
          "Saguenay",
          "Saint-Adolphe-d'Howard",
          "Saint-Agapit",
          "Saint-Aimé-des-Lacs",
          "Saint-Alban",
          "Saint-Albert",
          "Saint-Alexandre",
          "Saint-Alexandre-de-Kamouraska",
          "Saint-Alexis",
          "Saint-Alexis-des-Monts",
          "Saint-Alphonse-de-Granby",
          "Saint-Alphonse-Rodriguez",
          "Saint-Amable",
          "Saint-Ambroise",
          "Saint-Ambroise-de-Kildare",
          "Saint-Anaclet-de-Lessard",
          "Saint-André-Avellin",
          "Saint-André-d'Argenteuil",
          "Saint-Anicet",
          "Saint-Anselme",
          "Saint-Antoine-de-Tilly",
          "Saint-Antoine-sur-Richelieu",
          "Saint-Antonin",
          "Saint-Apollinaire",
          "Saint-Armand",
          "Saint-Arsène",
          "Saint-Aubert",
          "Saint-Augustin-de-Desmaures",
          "Saint-Barnabé",
          "Saint-Barthélemy",
          "Saint-Basile",
          "Saint-Basile-le-Grand",
          "Saint-Benoît-Labre",
          "Saint-Bernard",
          "Saint-Bernard-de-Lacolle",
          "Saint-Blaise-sur-Richelieu",
          "Saint-Bonaventure",
          "Saint-Boniface",
          "Saint-Bruno",
          "Saint-Bruno-de-Guigues",
          "Saint-Bruno-de-Montarville",
          "Saint-Calixte",
          "Saint-Casimir",
          "Saint-Césaire",
          "Saint-Charles-Borromée",
          "Saint-Charles-de-Bellechasse",
          "Saint-Charles-sur-Richelieu",
          "Saint-Christophe-d'Arthabaska",
          "Saint-Chrysostome",
          "Saint-Claude",
          "Saint-Clet",
          "Saint-Colomban",
          "Saint-Côme",
          "Saint-Côme--Linière",
          "Saint-Constant",
          "Saint-Cuthbert",
          "Saint-Cyprien",
          "Saint-Cyprien-de-Napierville",
          "Saint-Cyrille-de-Wendover",
          "Saint-Damase",
          "Saint-Damien",
          "Saint-Damien-de-Buckland",
          "Saint-David-de-Falardeau",
          "Saint-Denis",
          "Saint-Denis-de-Brompton",
          "Saint-Dominique",
          "Saint-Donat",
          "Saint-Édouard",
          "Saint-Édouard-de-Lotbinière",
          "Saint-Élie-de-Caxton",
          "Saint-Elzéar",
          "Saint-Éphrem-de-Beauce",
          "Saint-Esprit",
          "Saint-Étienne-des-Grès",
          "Saint-Eugène",
          "Saint-Eustache",
          "Saint-Fabien",
          "Saint-Faustin--Lac-Carré",
          "Saint-Félicien",
          "Saint-Félix-de-Kingsey",
          "Saint-Félix-de-Valois",
          "Saint-Ferdinand",
          "Saint-Ferréol-les-Neiges",
          "Saint-Flavien",
          "Saint-François-de-la-Rivière-du-Sud",
          "Saint-François-du-Lac",
          "Saint-François-Xavier-de-Brompton",
          "Saint-Frédéric",
          "Saint-Fulgence",
          "Saint-Gabriel",
          "Saint-Gabriel-de-Brandon",
          "Saint-Gabriel-de-Rimouski",
          "Saint-Gabriel-de-Valcartier",
          "Saint-Gédéon",
          "Saint-Gédéon-de-Beauce",
          "Saint-Georges-de-Cacouna",
          "Saint-Georges-de-Clarenceville",
          "Saint-Germain-de-Grantham",
          "Saint-Gervais",
          "Saint-Gilles",
          "Saint-Guillaume",
          "Saint-Henri",
          "Saint-Hilarion",
          "Saint-Hippolyte",
          "Saint-Honoré",
          "Saint-Honoré-de-Shenley",
          "Saint-Hubert-de-Rivière-du-Loup",
          "Saint-Hugues",
          "Saint-Hyacinthe",
          "Saint-Ignace-de-Loyola",
          "Saint-Isidore",
          "Saint-Jacques",
          "Saint-Jacques-le-Mineur",
          "Saint-Jean-Baptiste",
          "Saint-Jean-de-Dieu",
          "Saint-Jean-de-Matha",
          "Saint-Jean-Port-Joli",
          "Saint-Jean-sur-Richelieu",
          "Saint-Jérôme",
          "Saint-Joachim",
          "Saint-Joachim-de-Shefford",
          "Saint-Joseph-de-Beauce",
          "Saint-Joseph-de-Coleraine",
          "Saint-Joseph-de-Sorel",
          "Saint-Joseph-du-Lac",
          "Saint-Jude",
          "Saint-Justin",
          "Saint-Lambert",
          "Saint-Lambert-de-Lauzon",
          "Saint-Laurent-de-l'Île-d'Orléans",
          "Saint-Lazare",
          "Saint-Lazare-de-Bellechasse",
          "Saint-Léon-de-Standon",
          "Saint-Léonard-d'Aston",
          "Saint-Léonard-de-Portneuf",
          "Saint-Liboire",
          "Saint-Liguori",
          "Saint-Lin--Laurentides",
          "Saint-Louis-de-Gonzague",
          "Saint-Louis-du-Ha! Ha!",
          "Saint-Lucien",
          "Saint-Ludger",
          "Saint-Majorique-de-Grantham",
          "Saint-Malachie",
          "Saint-Marc-des-Carrières",
          "Saint-Marc-sur-Richelieu",
          "Saint-Martin",
          "Saint-Mathias-sur-Richelieu",
          "Saint-Mathieu",
          "Saint-Mathieu-de-Beloeil",
          "Saint-Mathieu-du-Parc",
          "Saint-Maurice",
          "Saint-Maxime-du-Mont-Louis",
          "Saint-Michel",
          "Saint-Michel-de-Bellechasse",
          "Saint-Michel-des-Saints",
          "Saint-Michel-du-Squatec",
          "Saint-Modeste",
          "Saint-Narcisse",
          "Saint-Narcisse-de-Beaurivage",
          "Saint-Narcisse-de-Rimouski",
          "Saint-Nazaire",
          "Saint-Norbert",
          "Saint-Norbert-d'Arthabaska",
          "Saint-Odilon-de-Cranbourne",
          "Saint-Ours",
          "Saint-Pacôme",
          "Saint-Pamphile",
          "Saint-Pascal",
          "Saint-Patrice-de-Beaurivage",
          "Saint-Patrice-de-Sherrington",
          "Saint-Paul",
          "Saint-Paul-d'Abbotsford",
          "Saint-Paul-de-l'Île-aux-Noix",
          "Saint-Paulin",
          "Saint-Philippe",
          "Saint-Pie",
          "Saint-Pierre-de-l'Île-d'Orléans",
          "Saint-Pierre-les-Becquets",
          "Saint-Placide",
          "Saint-Polycarpe",
          "Saint-Prime",
          "Saint-Prosper",
          "Saint-Raphaël",
          "Saint-Raymond",
          "Saint-Rémi",
          "Saint-René-de-Matane",
          "Saint-Robert",
          "Saint-Roch-de-l'Achigan",
          "Saint-Roch-de-Richelieu",
          "Saint-Sauveur",
          "Saint-Siméon",
          "Saint-Simon",
          "Saint-Stanislas",
          "Saint-Stanislas-de-Kostka",
          "Saint-Sulpice",
          "Saint-Sylvestre",
          "Saint-Théodore-d'Acton",
          "Saint-Thomas",
          "Saint-Tite",
          "Saint-Tite-des-Caps",
          "Saint-Ubalde",
          "Saint-Urbain",
          "Saint-Urbain-Premier",
          "Saint-Valère",
          "Saint-Valérien-de-Milton",
          "Saint-Vallier",
          "Saint-Victor",
          "Saint-Wenceslas",
          "Saint-Zacharie",
          "Saint-Zénon",
          "Saint-Zotique",
          "Sainte-Adèle",
          "Sainte-Agathe-de-Lotbinière",
          "Sainte-Agathe-des-Monts",
          "Sainte-Angèle-de-Monnoir",
          "Sainte-Anne-de-Beaupré",
          "Sainte-Anne-de-Bellevue",
          "Sainte-Anne-de-la-Pérade",
          "Sainte-Anne-de-la-Pocatière",
          "Sainte-Anne-de-Sabrevois",
          "Sainte-Anne-de-Sorel",
          "Sainte-Anne-des-Lacs",
          "Sainte-Anne-des-Monts",
          "Sainte-Anne-des-Plaines",
          "Sainte-Anne-du-Sault",
          "Sainte-Barbe",
          "Sainte-Béatrix",
          "Sainte-Brigide-d'Iberville",
          "Sainte-Brigitte-de-Laval",
          "Sainte-Catherine",
          "Sainte-Catherine-de-Hatley",
          "Sainte-Catherine-de-la-Jacques-Cartier",
          "Sainte-Cécile-de-Milton",
          "Sainte-Claire",
          "Sainte-Clotilde",
          "Sainte-Clotilde-de-Horton",
          "Sainte-Croix",
          "Sainte-Élisabeth",
          "Sainte-Émélie-de-l'Énergie",
          "Sainte-Félicité",
          "Sainte-Geneviève-de-Batiscan",
          "Sainte-Geneviève-de-Berthier",
          "Sainte-Hélène-de-Bagot",
          "Sainte-Hénédine",
          "Sainte-Jeanne-d'Arc",
          "Sainte-Julie",
          "Sainte-Julienne",
          "Sainte-Justine",
          "Sainte-Luce",
          "Sainte-Lucie-des-Laurentides",
          "Sainte-Madeleine",
          "Sainte-Marcelline-de-Kildare",
          "Sainte-Marguerite",
          "Sainte-Marguerite-du-Lac-Masson",
          "Sainte-Marie",
          "Sainte-Marie-Madeleine",
          "Sainte-Marie-Salomé",
          "Sainte-Marthe",
          "Sainte-Marthe-sur-le-Lac",
          "Sainte-Martine",
          "Sainte-Mélanie",
          "Sainte-Pétronille",
          "Sainte-Sabine",
          "Sainte-Sophie",
          "Sainte-Thècle",
          "Sainte-Thérèse",
          "Sainte-Thérèse-de-Gaspé",
          "Sainte-Ursule",
          "Sainte-Victoire-de-Sorel",
          "Saints-Anges",
          "Salaberry-de-Valleyfield",
          "Salluit",
          "Sayabec",
          "Scott",
          "Senneterre",
          "Sept-Îles",
          "Shannon",
          "Shawinigan",
          "Shawville",
          "Sherbrooke",
          "Sorel-Tracy",
          "Stanstead",
          "Stoke",
          "Stoneham-et-Tewkesbury",
          "Stukely-Sud",
          "Sutton",
          "Témiscaming",
          "Témiscouata-sur-le-Lac",
          "Terrasse-Vaudreuil",
          "Terrebonne",
          "Thetford Mines",
          "Thurso",
          "Tingwick",
          "Trécesson",
          "Très-Saint-Sacrement",
          "Tring-Jonction",
          "Trois-Pistoles",
          "Trois-Rivières",
          "Uashat",
          "Upton",
          "Val-David",
          "Val-des-Monts",
          "Val-d’Or",
          "Val-Joli",
          "Val-Morin",
          "Val-Shefford",
          "Valcourt",
          "Vallée-Jonction",
          "Varennes",
          "Vaudreuil-Dorion",
          "Vaudreuil-sur-le-Lac",
          "Venise-en-Québec",
          "Verchères",
          "Victoriaville",
          "Ville-Marie",
          "Warwick",
          "Waskaganish",
          "Waswanipi",
          "Waterloo",
          "Waterville",
          "Weedon-Centre",
          "Wemindji",
          "Wemotaci",
          "Wendake",
          "Wentworth-Nord",
          "Westmount",
          "Wickham",
          "Windsor",
          "Wotton",
          "Yamachiche",
          "Yamaska",
          "Yamaska-Est",
        ],
      },
      {
        name: "Saskatchewan",
        taxPercantage: 5,
        cities: [
          "Air Ronge",
          "Assiniboia",
          "Balgonie",
          "Battle River No. 438",
          "Battleford",
          "Beaver River",
          "Biggar",
          "Birch Hills",
          "Blucher",
          "Britannia No. 502",
          "Buckland No. 491",
          "Buffalo Narrows",
          "Canora",
          "Canwood No. 494",
          "Carlyle",
          "Carnduff",
          "Corman Park No. 344",
          "Creighton",
          "Dalmeny",
          "Davidson",
          "Delisle",
          "Duck Lake No. 463",
          "Dundurn No. 314",
          "Edenwold No. 158",
          "Esterhazy",
          "Estevan",
          "Estevan No. 5",
          "Eston",
          "Flin Flon",
          "Foam Lake",
          "Fort Qu’Appelle",
          "Frenchman Butte",
          "Gravelbourg",
          "Grenfell",
          "Hudson Bay",
          "Hudson Bay No. 394",
          "Humboldt",
          "Ile-à-la-Crosse",
          "Indian Head",
          "Kamsack",
          "Kerrobert",
          "Kindersley",
          "Kindersley No. 290",
          "Kipling",
          "La Loche",
          "La Ronge",
          "Laird No. 404",
          "Lajord No. 128",
          "Langenburg",
          "Langham",
          "Lanigan",
          "Lloydminster",
          "Longlaketon No. 219",
          "Lumsden",
          "Lumsden No. 189",
          "Macklin",
          "Maidstone",
          "Maple Creek",
          "Maple Creek No. 111",
          "Martensville",
          "Meadow Lake",
          "Meadow Lake No. 588",
          "Melfort",
          "Melville",
          "Mervin No. 499",
          "Moose Jaw",
          "Moose Jaw No. 161",
          "Moosomin",
          "Nipawin",
          "Nipawin No. 487",
          "North Battleford",
          "Orkney No. 244",
          "Osler",
          "Outlook",
          "Oxbow",
          "Pelican Narrows",
          "Pilot Butte",
          "Pinehouse",
          "Preeceville",
          "Prince Albert",
          "Prince Albert No. 461",
          "Rama",
          "Regina",
          "Regina Beach",
          "Rosetown",
          "Rosthern",
          "Rosthern No. 403",
          "Saskatoon",
          "Shaunavon",
          "Shellbrook",
          "Shellbrook No. 493",
          "South Qu'Appelle No. 157",
          "Spiritwood No. 496",
          "St. Louis No. 431",
          "Swift Current",
          "Swift Current No. 137",
          "Tisdale",
          "Torch River No. 488",
          "Unity",
          "Vanscoy No. 345",
          "Wadena",
          "Waldheim",
          "Warman",
          "Watrous",
          "Weyburn",
          "Weyburn No. 67",
          "White City",
          "Wilkie",
          "Wilton No. 472",
          "Wynyard",
          "Yorkton",
        ],
      },
      {
        name: "Yukon",
        taxPercantage: 5,
        cities: ["Dawson", "Whitehorse"],
      },
      {
        name: "Ontario",
        taxPercantage: 13,
        cities: [
          "Addington Highlands",
          "Adelaide-Metcalfe",
          "Adjala-Tosorontio",
          "Admaston/Bromley",
          "Ajax",
          "Alfred and Plantagenet",
          "Algonquin Highlands",
          "Alnwick/Haldimand",
          "Alvinston",
          "Amaranth",
          "Amherstburg",
          "Armour",
          "Armstrong",
          "Arnprior",
          "Arran-Elderslie",
          "Ashfield-Colborne-Wawanosh",
          "Asphodel-Norwood",
          "Assiginack",
          "Athens",
          "Atikokan",
          "Augusta",
          "Aurora",
          "Aylmer",
          "Bancroft",
          "Barrie",
          "Bayfield",
          "Bayham",
          "Beachburg",
          "Beckwith",
          "Belleville",
          "Black River-Matheson",
          "Blandford-Blenheim",
          "Blind River",
          "Bluewater",
          "Bonfield",
          "Bonnechere Valley",
          "Bracebridge",
          "Bradford West Gwillimbury",
          "Brampton",
          "Brant",
          "Brantford",
          "Breslau",
          "Brighton",
          "Brock",
          "Brockton",
          "Brockville",
          "Brudenell, Lyndoch and Raglan",
          "Burford",
          "Burlington",
          "Caledon",
          "Callander",
          "Cambridge",
          "Carleton Place",
          "Carling",
          "Casselman",
          "Cavan Monaghan",
          "Central Elgin",
          "Central Frontenac",
          "Central Huron",
          "Central Manitoulin",
          "Centre Hastings",
          "Centre Wellington",
          "Champlain",
          "Chapleau",
          "Chatham",
          "Chatsworth",
          "Chisholm",
          "Claremont",
          "Clarence-Rockland",
          "Clarington",
          "Clearview",
          "Cobalt",
          "Cobourg",
          "Cochrane",
          "Collingwood",
          "Conestogo",
          "Cornwall",
          "Cramahe",
          "Dawn-Euphemia",
          "Deep River",
          "Deseronto",
          "Douro-Dummer",
          "Drummond/North Elmsley",
          "Dryden",
          "Dutton/Dunwich",
          "Dysart et al",
          "East Ferris",
          "East Garafraxa",
          "East Gwillimbury",
          "East Hawkesbury",
          "East Zorra-Tavistock",
          "Edwardsburgh/Cardinal",
          "Elizabethtown-Kitley",
          "Elliot Lake",
          "Emo",
          "Englehart",
          "Enniskillen",
          "Erin",
          "Espanola",
          "Essa",
          "Essex",
          "Faraday",
          "Fort Erie",
          "Fort Frances",
          "French River / Rivière des Français",
          "Front of Yonge",
          "Frontenac Islands",
          "Gananoque",
          "Georgian Bay",
          "Georgian Bluffs",
          "Georgina",
          "Goderich",
          "Grand Valley",
          "Gravenhurst",
          "Greater Madawaska",
          "Greater Napanee",
          "Greenstone",
          "Grey Highlands",
          "Grimsby",
          "Guelph",
          "Guelph/Eramosa",
          "Halton Hills",
          "Hamilton",
          "Hamilton Township",
          "Hanover",
          "Hastings Highlands",
          "Havelock-Belmont-Methuen",
          "Hawkesbury",
          "Hearst",
          "Hensall",
          "Highlands East",
          "Hillsburgh",
          "Hindon Hill",
          "Horton",
          "Howick",
          "Huntsville",
          "Huron East",
          "Huron Shores",
          "Huron-Kinloss",
          "Ignace",
          "Ingersoll",
          "Innisfil",
          "Iroquois Falls",
          "Kapuskasing",
          "Kawartha Lakes",
          "Kenora",
          "Killaloe, Hagarty and Richards",
          "Kincardine",
          "King",
          "Kingsville",
          "Kirkland Lake",
          "Kitchener",
          "Komoka",
          "Laird",
          "Lake of Bays",
          "Lakeshore",
          "Lambton Shores",
          "Lanark Highlands",
          "Lappe",
          "LaSalle",
          "Laurentian Hills",
          "Laurentian Valley",
          "Leamington",
          "Leeds and the Thousand Islands",
          "Lincoln",
          "London",
          "Loyalist",
          "Lucan Biddulph",
          "Macdonald, Meredith and Aberdeen Additional",
          "Madawaska Valley",
          "Madoc",
          "Magnetawan",
          "Malahide",
          "Manitouwadge",
          "Mapleton",
          "Marathon",
          "Markham",
          "Markstay",
          "Marmora and Lake",
          "Mattawa",
          "McDougall",
          "McKellar",
          "McNab/Braeside",
          "Meaford",
          "Melancthon",
          "Merrickville",
          "Middlesex Centre",
          "Midland",
          "Milton",
          "Minto",
          "Mississauga",
          "Mississippi Mills",
          "Mono",
          "Montague",
          "Moonbeam",
          "Moosonee",
          "Morris-Turnberry",
          "Mulmur",
          "Muskoka Falls",
          "Neebing",
          "New Tecumseth",
          "Newmarket",
          "Niagara Falls",
          "Niagara-on-the-Lake",
          "Nipigon",
          "Nipissing",
          "North Algona Wilberforce",
          "North Bay",
          "North Dumfries",
          "North Dundas",
          "North Frontenac",
          "North Glengarry",
          "North Grenville",
          "North Huron",
          "North Kawartha",
          "North Middlesex",
          "North Perth",
          "North Stormont",
          "Northeastern Manitoulin and the Islands",
          "Northern Bruce Peninsula",
          "Norwich",
          "Oakville",
          "Oliver Paipoonge",
          "Orangeville",
          "Orillia",
          "Oro-Medonte",
          "Oshawa",
          "Otonabee-South Monaghan",
          "Ottawa",
          "Owen Sound",
          "Papineau-Cameron",
          "Parry Sound",
          "Pelham",
          "Pembroke",
          "Penetanguishene",
          "Perry",
          "Perth",
          "Perth East",
          "Perth South",
          "Petawawa",
          "Peterborough",
          "Petrolia",
          "Pickering",
          "Plantagenet",
          "Plympton-Wyoming",
          "Point Edward",
          "Port Colborne",
          "Port Hope",
          "Powassan",
          "Prescott",
          "Prince",
          "Puslinch",
          "Quinte West",
          "Ramara",
          "Red Lake",
          "Renfrew",
          "Richmond Hill",
          "Rideau Lakes",
          "Russell",
          "Sables-Spanish Rivers",
          "Sagamok",
          "Sarnia",
          "Saugeen Shores",
          "Sault Ste. Marie",
          "Schreiber",
          "Scugog",
          "Seguin",
          "Selwyn",
          "Severn",
          "Shelburne",
          "Shuniah",
          "Sioux Lookout",
          "Sioux Narrows-Nestor Falls",
          "Smiths Falls",
          "Smooth Rock Falls",
          "South Algonquin",
          "South Bruce",
          "South Bruce Peninsula",
          "South Dundas",
          "South Frontenac",
          "South Glengarry",
          "South Huron",
          "South River",
          "South Stormont",
          "South-West Oxford",
          "Southgate",
          "Southwest Middlesex",
          "Southwold",
          "Springwater",
          "St. Catharines",
          "St. Clair",
          "St. Joseph",
          "St. Marys",
          "St. Thomas",
          "St.-Charles",
          "Stirling-Rawdon",
          "Stone Mills",
          "Stouffville",
          "Stratford",
          "Strathroy-Caradoc",
          "Strong",
          "Sudbury",
          "Tara",
          "Tay",
          "Tay Valley",
          "Tecumseh",
          "Temiskaming Shores",
          "Terrace Bay",
          "Thames Centre",
          "The Blue Mountains",
          "The Nation / La Nation",
          "Thessalon",
          "Thorold",
          "Thunder Bay",
          "Tillsonburg",
          "Timmins",
          "Tiny",
          "Toronto",
          "Trent Hills",
          "Trent Lakes",
          "Tweed",
          "Tyendinaga",
          "Uxbridge",
          "Vaughan",
          "Wainfleet",
          "Warwick",
          "Wasaga Beach",
          "Waterloo",
          "Wawa",
          "Welland",
          "Wellesley",
          "Wellington",
          "Wellington North",
          "West Elgin",
          "West Grey",
          "West Lincoln",
          "West Nipissing / Nipissing Ouest",
          "West Perth",
          "Whitby",
          "Whitewater Region",
          "Wilmot",
          "Windsor",
          "Woodstock",
          "Woolwich",
          "Zorra",
        ],
      },
      {
        name: "New Brunswick",
        taxPercantage: 15,
        cities: [
          "Allardville",
          "Alnwick",
          "Atholville",
          "Balmoral",
          "Bas Caraquet",
          "Bathurst",
          "Beaubassin East / Beaubassin-est",
          "Belledune",
          "Beresford",
          "Bertrand",
          "Botsford",
          "Bright",
          "Brighton",
          "Buctouche",
          "Burton",
          "Campbellton",
          "Cap Pele",
          "Caraquet",
          "Cardwell",
          "Charlo",
          "Chipman",
          "Cocagne",
          "Coverdale",
          "Dalhousie",
          "Denmark",
          "Dieppe",
          "Dorchester",
          "Douglas",
          "Dundas",
          "Durham",
          "Edmundston",
          "Eel River Crossing",
          "Florenceville",
          "Fredericton",
          "Glenelg",
          "Gordon",
          "Grand Bay-Westfield",
          "Grand Falls",
          "Grand Manan",
          "Greenwich",
          "Hampton",
          "Hanwell",
          "Hardwicke",
          "Havelock",
          "Hillsborough",
          "Kedgwick",
          "Kent",
          "Kingsclear",
          "Kingston",
          "Lamèque",
          "Lincoln",
          "Manners Sutton",
          "Maugerville",
          "McAdam",
          "Memramcook",
          "Minto",
          "Miramichi",
          "Moncton",
          "Musquash",
          "Nauwigewauk",
          "Neguac",
          "New Bandon",
          "New Maryland",
          "Newcastle",
          "Noonan",
          "Northampton",
          "Northesk",
          "Norton",
          "Oromocto",
          "Paquetville",
          "Peel",
          "Pennfield Ridge",
          "Perth",
          "Petit Rocher",
          "Petitcodiac",
          "Plaster Rock",
          "Queensbury",
          "Quispamsis",
          "Richibucto",
          "Richmond",
          "Riverview",
          "Rogersville",
          "Rothesay",
          "Sackville",
          "Saint Andrews",
          "Saint David",
          "Saint George",
          "Saint James",
          "Saint John",
          "Saint Martins",
          "Saint Mary",
          "Saint Marys",
          "Saint Stephen",
          "Saint-André",
          "Saint-Antoine",
          "Saint-Charles",
          "Saint-Jacques",
          "Saint-Joseph",
          "Saint-Léonard",
          "Saint-Louis",
          "Saint-Quentin",
          "Salisbury",
          "Shediac",
          "Shippagan",
          "Shippegan",
          "Simonds",
          "Southampton",
          "Southesk",
          "Springfield",
          "St. George",
          "Studholm",
          "Sussex",
          "Sussex Corner",
          "Tracadie",
          "Upham",
          "Upper Miramichi",
          "Wakefield",
          "Weldford",
          "Wellington",
          "Westfield Beach",
          "Wicklow",
          "Wilmot",
          "Woodstock",
        ],
      },
      {
        name: "Newfoundland and Labrador",
        taxPercantage: 15,
        cities: [
          "Baie Verte",
          "Bay Bulls",
          "Bay Roberts",
          "Bishops Falls",
          "Bonavista",
          "Botwood",
          "Burgeo",
          "Burin",
          "Carbonear",
          "Centreville-Wareham-Trinity",
          "Channel-Port aux Basques",
          "Clarenville",
          "Clarkes Beach",
          "Conception Bay South",
          "Corner Brook",
          "Deer Lake",
          "Dildo",
          "Flat Rock",
          "Fogo Island",
          "Fortune",
          "Gambo",
          "Gander",
          "Glovertown",
          "Goulds",
          "Grand Bank",
          "Grand Falls",
          "Happy Valley",
          "Harbour Breton",
          "Harbour Grace",
          "Harbour Main-Chapel's Cove-Lakeview",
          "Holyrood",
          "Humbermouth",
          "Irishtown-Summerside",
          "Kippens",
          "Labrador City",
          "Lewisporte",
          "Logy Bay-Middle Cove-Outer Cove",
          "Marystown",
          "Massey Drive",
          "Mount Pearl Park",
          "Nain",
          "New-Wes-Valley",
          "Paradise",
          "Pasadena",
          "Placentia",
          "Portugal Cove-St. Philip's",
          "Pouch Cove",
          "Spaniards Bay",
          "Springdale",
          "St. Alban's",
          "St. Anthony",
          "St. George's",
          "St. John's",
          "St. Lawrence",
          "Stephenville",
          "Stephenville Crossing",
          "Torbay",
          "Trinity Bay North",
          "Twillingate",
          "Upper Island Cove",
          "Victoria",
          "Wabana",
          "Wabush",
          "Witless Bay",
        ],
      },
      {
        name: "Nova Scotia",
        taxPercantage: 15,
        cities: [
          "Amherst",
          "Antigonish",
          "Argyle",
          "Barrington",
          "Berwick",
          "Bridgewater",
          "Cape Breton",
          "Centreville",
          "Chester",
          "Church Point",
          "Digby",
          "Falmouth",
          "Halifax",
          "Inverness",
          "Kentville",
          "Lantz",
          "Lunenburg",
          "Mahone Bay",
          "Middleton",
          "New Glasgow",
          "Oxford",
          "Parrsboro",
          "Pictou",
          "Port Hawkesbury",
          "Queens",
          "Shelburne",
          "Stellarton",
          "Stewiacke",
          "Trenton",
          "Truro",
          "Wedgeport",
          "Westville",
          "Windsor",
          "Wolfville",
          "Yarmouth",
        ],
      },
      {
        name: "Prince Edward Island",
        taxPercantage: 15,
        cities: [
          "Alberton",
          "Charlottetown",
          "Cornwall",
          "Kensington",
          "Malpeque",
          "Miltonvale Park",
          "Montague",
          "Souris",
          "Stratford",
          "Summerside",
        ],
      },
    ],
  },
  usa: {
    shipping: 200,
    items: {
      "New York": [
        "New York",
        "Buffalo",
        "Rochester",
        "Yonkers",
        "Syracuse",
        "Albany",
        "New Rochelle",
        "Mount Vernon",
        "Schenectady",
        "Utica",
        "White Plains",
        "Hempstead",
        "Troy",
        "Niagara Falls",
        "Binghamton",
        "Freeport",
        "Valley Stream",
      ],
      California: [
        "Los Angeles",
        "San Diego",
        "San Jose",
        "San Francisco",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Oakland",
        "Bakersfield",
        "Anaheim",
        "Santa Ana",
        "Riverside",
        "Stockton",
        "Chula Vista",
        "Irvine",
        "Fremont",
        "San Bernardino",
        "Modesto",
        "Fontana",
        "Oxnard",
        "Moreno Valley",
        "Huntington Beach",
        "Glendale",
        "Santa Clarita",
        "Garden Grove",
        "Oceanside",
        "Rancho Cucamonga",
        "Santa Rosa",
        "Ontario",
        "Lancaster",
        "Elk Grove",
        "Corona",
        "Palmdale",
        "Salinas",
        "Pomona",
        "Hayward",
        "Escondido",
        "Torrance",
        "Sunnyvale",
        "Orange",
        "Fullerton",
        "Pasadena",
        "Thousand Oaks",
        "Visalia",
        "Simi Valley",
        "Concord",
        "Roseville",
        "Victorville",
        "Santa Clara",
        "Vallejo",
        "Berkeley",
        "El Monte",
        "Downey",
        "Costa Mesa",
        "Inglewood",
        "Carlsbad",
        "San Buenaventura (Ventura)",
        "Fairfield",
        "West Covina",
        "Murrieta",
        "Richmond",
        "Norwalk",
        "Antioch",
        "Temecula",
        "Burbank",
        "Daly City",
        "Rialto",
        "Santa Maria",
        "El Cajon",
        "San Mateo",
        "Clovis",
        "Compton",
        "Jurupa Valley",
        "Vista",
        "South Gate",
        "Mission Viejo",
        "Vacaville",
        "Carson",
        "Hesperia",
        "Santa Monica",
        "Westminster",
        "Redding",
        "Santa Barbara",
        "Chico",
        "Newport Beach",
        "San Leandro",
        "San Marcos",
        "Whittier",
        "Hawthorne",
        "Citrus Heights",
        "Tracy",
        "Alhambra",
        "Livermore",
        "Buena Park",
        "Menifee",
        "Hemet",
        "Lakewood",
        "Merced",
        "Chino",
        "Indio",
        "Redwood City",
        "Lake Forest",
        "Napa",
        "Tustin",
        "Bellflower",
        "Mountain View",
        "Chino Hills",
        "Baldwin Park",
        "Alameda",
        "Upland",
        "San Ramon",
        "Folsom",
        "Pleasanton",
        "Union City",
        "Perris",
        "Manteca",
        "Lynwood",
        "Apple Valley",
        "Redlands",
        "Turlock",
        "Milpitas",
        "Redondo Beach",
        "Rancho Cordova",
        "Yorba Linda",
        "Palo Alto",
        "Davis",
        "Camarillo",
        "Walnut Creek",
        "Pittsburg",
        "South San Francisco",
        "Yuba City",
        "San Clemente",
        "Laguna Niguel",
        "Pico Rivera",
        "Montebello",
        "Lodi",
        "Madera",
        "Santa Cruz",
        "La Habra",
        "Encinitas",
        "Monterey Park",
        "Tulare",
        "Cupertino",
        "Gardena",
        "National City",
        "Rocklin",
        "Petaluma",
        "Huntington Park",
        "San Rafael",
        "La Mesa",
        "Arcadia",
        "Fountain Valley",
        "Diamond Bar",
        "Woodland",
        "Santee",
        "Lake Elsinore",
        "Porterville",
        "Paramount",
        "Eastvale",
        "Rosemead",
        "Hanford",
        "Highland",
        "Brentwood",
        "Novato",
        "Colton",
        "Cathedral City",
        "Delano",
        "Yucaipa",
        "Watsonville",
        "Placentia",
        "Glendora",
        "Gilroy",
        "Palm Desert",
        "Cerritos",
        "West Sacramento",
        "Aliso Viejo",
        "Poway",
        "La Mirada",
        "Rancho Santa Margarita",
        "Cypress",
        "Dublin",
        "Covina",
        "Azusa",
        "Palm Springs",
        "San Luis Obispo",
        "Ceres",
        "San Jacinto",
        "Lincoln",
        "Newark",
        "Lompoc",
        "El Centro",
        "Danville",
        "Bell Gardens",
        "Coachella",
        "Rancho Palos Verdes",
        "San Bruno",
        "Rohnert Park",
        "Brea",
        "La Puente",
        "Campbell",
        "San Gabriel",
        "Beaumont",
        "Morgan Hill",
        "Culver City",
        "Calexico",
        "Stanton",
        "La Quinta",
        "Pacifica",
        "Montclair",
        "Oakley",
        "Monrovia",
        "Los Banos",
        "Martinez",
      ],
      Illinois: [
        "Chicago",
        "Aurora",
        "Rockford",
        "Joliet",
        "Naperville",
        "Springfield",
        "Peoria",
        "Elgin",
        "Waukegan",
        "Cicero",
        "Champaign",
        "Bloomington",
        "Arlington Heights",
        "Evanston",
        "Decatur",
        "Schaumburg",
        "Bolingbrook",
        "Palatine",
        "Skokie",
        "Des Plaines",
        "Orland Park",
        "Tinley Park",
        "Oak Lawn",
        "Berwyn",
        "Mount Prospect",
        "Normal",
        "Wheaton",
        "Hoffman Estates",
        "Oak Park",
        "Downers Grove",
        "Elmhurst",
        "Glenview",
        "DeKalb",
        "Lombard",
        "Belleville",
        "Moline",
        "Buffalo Grove",
        "Bartlett",
        "Urbana",
        "Quincy",
        "Crystal Lake",
        "Plainfield",
        "Streamwood",
        "Carol Stream",
        "Romeoville",
        "Rock Island",
        "Hanover Park",
        "Carpentersville",
        "Wheeling",
        "Park Ridge",
        "Addison",
        "Calumet City",
      ],
      Texas: [
        "Houston",
        "San Antonio",
        "Dallas",
        "Austin",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
        "Lubbock",
        "Garland",
        "Irving",
        "Amarillo",
        "Grand Prairie",
        "Brownsville",
        "Pasadena",
        "McKinney",
        "Mesquite",
        "McAllen",
        "Killeen",
        "Frisco",
        "Waco",
        "Carrollton",
        "Denton",
        "Midland",
        "Abilene",
        "Beaumont",
        "Round Rock",
        "Odessa",
        "Wichita Falls",
        "Richardson",
        "Lewisville",
        "Tyler",
        "College Station",
        "Pearland",
        "San Angelo",
        "Allen",
        "League City",
        "Sugar Land",
        "Longview",
        "Edinburg",
        "Mission",
        "Bryan",
        "Baytown",
        "Pharr",
        "Temple",
        "Missouri City",
        "Flower Mound",
        "Harlingen",
        "North Richland Hills",
        "Victoria",
        "Conroe",
        "New Braunfels",
        "Mansfield",
        "Cedar Park",
        "Rowlett",
        "Port Arthur",
        "Euless",
        "Georgetown",
        "Pflugerville",
        "DeSoto",
        "San Marcos",
        "Grapevine",
        "Bedford",
        "Galveston",
        "Cedar Hill",
        "Texas City",
        "Wylie",
        "Haltom City",
        "Keller",
        "Coppell",
        "Rockwall",
        "Huntsville",
        "Duncanville",
        "Sherman",
        "The Colony",
        "Burleson",
        "Hurst",
        "Lancaster",
        "Texarkana",
        "Friendswood",
        "Weslaco",
      ],
      Pennsylvania: [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Scranton",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "Altoona",
        "York",
        "State College",
        "Wilkes-Barre",
      ],
      Arizona: [
        "Phoenix",
        "Tucson",
        "Mesa",
        "Chandler",
        "Glendale",
        "Scottsdale",
        "Gilbert",
        "Tempe",
        "Peoria",
        "Surprise",
        "Yuma",
        "Avondale",
        "Goodyear",
        "Flagstaff",
        "Buckeye",
        "Lake Havasu City",
        "Casa Grande",
        "Sierra Vista",
        "Maricopa",
        "Oro Valley",
        "Prescott",
        "Bullhead City",
        "Prescott Valley",
        "Marana",
        "Apache Junction",
      ],
      Florida: [
        "Jacksonville",
        "Miami",
        "Tampa",
        "Orlando",
        "St. Petersburg",
        "Hialeah",
        "Tallahassee",
        "Fort Lauderdale",
        "Port St. Lucie",
        "Cape Coral",
        "Pembroke Pines",
        "Hollywood",
        "Miramar",
        "Gainesville",
        "Coral Springs",
        "Miami Gardens",
        "Clearwater",
        "Palm Bay",
        "Pompano Beach",
        "West Palm Beach",
        "Lakeland",
        "Davie",
        "Miami Beach",
        "Sunrise",
        "Plantation",
        "Boca Raton",
        "Deltona",
        "Largo",
        "Deerfield Beach",
        "Palm Coast",
        "Melbourne",
        "Boynton Beach",
        "Lauderhill",
        "Weston",
        "Fort Myers",
        "Kissimmee",
        "Homestead",
        "Tamarac",
        "Delray Beach",
        "Daytona Beach",
        "North Miami",
        "Wellington",
        "North Port",
        "Jupiter",
        "Ocala",
        "Port Orange",
        "Margate",
        "Coconut Creek",
        "Sanford",
        "Sarasota",
        "Pensacola",
        "Bradenton",
        "Palm Beach Gardens",
        "Pinellas Park",
        "Coral Gables",
        "Doral",
        "Bonita Springs",
        "Apopka",
        "Titusville",
        "North Miami Beach",
        "Oakland Park",
        "Fort Pierce",
        "North Lauderdale",
        "Cutler Bay",
        "Altamonte Springs",
        "St. Cloud",
        "Greenacres",
        "Ormond Beach",
        "Ocoee",
        "Hallandale Beach",
        "Winter Garden",
        "Aventura",
      ],
      Indiana: [
        "Indianapolis",
        "Fort Wayne",
        "Evansville",
        "South Bend",
        "Carmel",
        "Bloomington",
        "Fishers",
        "Hammond",
        "Gary",
        "Muncie",
        "Lafayette",
        "Terre Haute",
        "Kokomo",
        "Anderson",
        "Noblesville",
        "Greenwood",
        "Elkhart",
        "Mishawaka",
        "Lawrence",
        "Jeffersonville",
        "Columbus",
        "Portage",
      ],
      Ohio: [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Parma",
        "Canton",
        "Youngstown",
        "Lorain",
        "Hamilton",
        "Springfield",
        "Kettering",
        "Elyria",
        "Lakewood",
        "Cuyahoga Falls",
        "Middletown",
        "Euclid",
        "Newark",
        "Mansfield",
        "Mentor",
        "Beavercreek",
        "Cleveland Heights",
        "Strongsville",
        "Dublin",
        "Fairfield",
        "Findlay",
        "Warren",
        "Lancaster",
        "Lima",
        "Huber Heights",
        "Westerville",
        "Marion",
        "Grove City",
      ],
      "North Carolina": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Wilmington",
        "High Point",
        "Greenville",
        "Asheville",
        "Concord",
        "Gastonia",
        "Jacksonville",
        "Chapel Hill",
        "Rocky Mount",
        "Burlington",
        "Wilson",
        "Huntersville",
        "Kannapolis",
        "Apex",
        "Hickory",
        "Goldsboro",
      ],
      Michigan: [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Ann Arbor",
        "Lansing",
        "Flint",
        "Dearborn",
        "Livonia",
        "Westland",
        "Troy",
        "Farmington Hills",
        "Kalamazoo",
        "Wyoming",
        "Southfield",
        "Rochester Hills",
        "Taylor",
        "Pontiac",
        "St. Clair Shores",
        "Royal Oak",
        "Novi",
        "Dearborn Heights",
        "Battle Creek",
        "Saginaw",
        "Kentwood",
        "East Lansing",
        "Roseville",
        "Portage",
        "Midland",
        "Lincoln Park",
        "Muskegon",
      ],
      Tennessee: [
        "Memphis",
        "Nashville-Davidson",
        "Knoxville",
        "Chattanooga",
        "Clarksville",
        "Murfreesboro",
        "Jackson",
        "Franklin",
        "Johnson City",
        "Bartlett",
        "Hendersonville",
        "Kingsport",
        "Collierville",
        "Cleveland",
        "Smyrna",
        "Germantown",
        "Brentwood",
      ],
      Massachusetts: [
        "Boston",
        "Worcester",
        "Springfield",
        "Lowell",
        "Cambridge",
        "New Bedford",
        "Brockton",
        "Quincy",
        "Lynn",
        "Fall River",
        "Newton",
        "Lawrence",
        "Somerville",
        "Waltham",
        "Haverhill",
        "Malden",
        "Medford",
        "Taunton",
        "Chicopee",
        "Weymouth Town",
        "Revere",
        "Peabody",
        "Methuen",
        "Barnstable Town",
        "Pittsfield",
        "Attleboro",
        "Everett",
        "Salem",
        "Westfield",
        "Leominster",
        "Fitchburg",
        "Beverly",
        "Holyoke",
        "Marlborough",
        "Woburn",
        "Chelsea",
      ],
      Washington: [
        "Seattle",
        "Spokane",
        "Tacoma",
        "Vancouver",
        "Bellevue",
        "Kent",
        "Everett",
        "Renton",
        "Yakima",
        "Federal Way",
        "Spokane Valley",
        "Bellingham",
        "Kennewick",
        "Auburn",
        "Pasco",
        "Marysville",
        "Lakewood",
        "Redmond",
        "Shoreline",
        "Richland",
        "Kirkland",
        "Burien",
        "Sammamish",
        "Olympia",
        "Lacey",
        "Edmonds",
        "Bremerton",
        "Puyallup",
      ],
      Colorado: [
        "Denver",
        "Colorado Springs",
        "Aurora",
        "Fort Collins",
        "Lakewood",
        "Thornton",
        "Arvada",
        "Westminster",
        "Pueblo",
        "Centennial",
        "Boulder",
        "Greeley",
        "Longmont",
        "Loveland",
        "Grand Junction",
        "Broomfield",
        "Castle Rock",
        "Commerce City",
        "Parker",
        "Littleton",
        "Northglenn",
      ],
      "District of Columbia": ["Washington"],
      Maryland: [
        "Baltimore",
        "Frederick",
        "Rockville",
        "Gaithersburg",
        "Bowie",
        "Hagerstown",
        "Annapolis",
      ],
      Kentucky: [
        "Louisville/Jefferson County",
        "Lexington-Fayette",
        "Bowling Green",
        "Owensboro",
        "Covington",
      ],
      Oregon: [
        "Portland",
        "Eugene",
        "Salem",
        "Gresham",
        "Hillsboro",
        "Beaverton",
        "Bend",
        "Medford",
        "Springfield",
        "Corvallis",
        "Albany",
        "Tigard",
        "Lake Oswego",
        "Keizer",
      ],
      Oklahoma: [
        "Oklahoma City",
        "Tulsa",
        "Norman",
        "Broken Arrow",
        "Lawton",
        "Edmond",
        "Moore",
        "Midwest City",
        "Enid",
        "Stillwater",
        "Muskogee",
      ],
      Wisconsin: [
        "Milwaukee",
        "Madison",
        "Green Bay",
        "Kenosha",
        "Racine",
        "Appleton",
        "Waukesha",
        "Eau Claire",
        "Oshkosh",
        "Janesville",
        "West Allis",
        "La Crosse",
        "Sheboygan",
        "Wauwatosa",
        "Fond du Lac",
        "New Berlin",
        "Wausau",
        "Brookfield",
        "Greenfield",
        "Beloit",
      ],
      Nevada: [
        "Las Vegas",
        "Henderson",
        "Reno",
        "North Las Vegas",
        "Sparks",
        "Carson City",
      ],
      "New Mexico": [
        "Albuquerque",
        "Las Cruces",
        "Rio Rancho",
        "Santa Fe",
        "Roswell",
        "Farmington",
        "Clovis",
      ],
      Missouri: [
        "Kansas City",
        "St. Louis",
        "Springfield",
        "Independence",
        "Columbia",
        "Lee's Summit",
        "O'Fallon",
        "St. Joseph",
        "St. Charles",
        "St. Peters",
        "Blue Springs",
        "Florissant",
        "Joplin",
        "Chesterfield",
        "Jefferson City",
        "Cape Girardeau",
      ],
      Virginia: [
        "Virginia Beach",
        "Norfolk",
        "Chesapeake",
        "Richmond",
        "Newport News",
        "Alexandria",
        "Hampton",
        "Roanoke",
        "Portsmouth",
        "Suffolk",
        "Lynchburg",
        "Harrisonburg",
        "Leesburg",
        "Charlottesville",
        "Danville",
        "Blacksburg",
        "Manassas",
      ],
      Georgia: [
        "Atlanta",
        "Columbus",
        "Augusta-Richmond County",
        "Savannah",
        "Athens-Clarke County",
        "Sandy Springs",
        "Roswell",
        "Macon",
        "Johns Creek",
        "Albany",
        "Warner Robins",
        "Alpharetta",
        "Marietta",
        "Valdosta",
        "Smyrna",
        "Dunwoody",
      ],
      Nebraska: ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
      Minnesota: [
        "Minneapolis",
        "St. Paul",
        "Rochester",
        "Duluth",
        "Bloomington",
        "Brooklyn Park",
        "Plymouth",
        "St. Cloud",
        "Eagan",
        "Woodbury",
        "Maple Grove",
        "Eden Prairie",
        "Coon Rapids",
        "Burnsville",
        "Blaine",
        "Lakeville",
        "Minnetonka",
        "Apple Valley",
        "Edina",
        "St. Louis Park",
        "Mankato",
        "Maplewood",
        "Moorhead",
        "Shakopee",
      ],
      Kansas: [
        "Wichita",
        "Overland Park",
        "Kansas City",
        "Olathe",
        "Topeka",
        "Lawrence",
        "Shawnee",
        "Manhattan",
        "Lenexa",
        "Salina",
        "Hutchinson",
      ],
      Louisiana: [
        "New Orleans",
        "Baton Rouge",
        "Shreveport",
        "Lafayette",
        "Lake Charles",
        "Kenner",
        "Bossier City",
        "Monroe",
        "Alexandria",
      ],
      Hawaii: ["Honolulu"],
      Alaska: ["Anchorage"],
      "New Jersey": [
        "Newark",
        "Jersey City",
        "Paterson",
        "Elizabeth",
        "Clifton",
        "Trenton",
        "Camden",
        "Passaic",
        "Union City",
        "Bayonne",
        "East Orange",
        "Vineland",
        "New Brunswick",
        "Hoboken",
        "Perth Amboy",
        "West New York",
        "Plainfield",
        "Hackensack",
        "Sayreville",
        "Kearny",
        "Linden",
        "Atlantic City",
      ],
      Idaho: [
        "Boise City",
        "Nampa",
        "Meridian",
        "Idaho Falls",
        "Pocatello",
        "Caldwell",
        "Coeur d'Alene",
        "Twin Falls",
      ],
      Alabama: [
        "Birmingham",
        "Montgomery",
        "Mobile",
        "Huntsville",
        "Tuscaloosa",
        "Hoover",
        "Dothan",
        "Auburn",
        "Decatur",
        "Madison",
        "Florence",
        "Gadsden",
      ],
      Iowa: [
        "Des Moines",
        "Cedar Rapids",
        "Davenport",
        "Sioux City",
        "Iowa City",
        "Waterloo",
        "Council Bluffs",
        "Ames",
        "West Des Moines",
        "Dubuque",
        "Ankeny",
        "Urbandale",
        "Cedar Falls",
      ],
      Arkansas: [
        "Little Rock",
        "Fort Smith",
        "Fayetteville",
        "Springdale",
        "Jonesboro",
        "North Little Rock",
        "Conway",
        "Rogers",
        "Pine Bluff",
        "Bentonville",
      ],
      Utah: [
        "Salt Lake City",
        "West Valley City",
        "Provo",
        "West Jordan",
        "Orem",
        "Sandy",
        "Ogden",
        "St. George",
        "Layton",
        "Taylorsville",
        "South Jordan",
        "Lehi",
        "Logan",
        "Murray",
        "Draper",
        "Bountiful",
        "Riverton",
        "Roy",
      ],
      "Rhode Island": [
        "Providence",
        "Warwick",
        "Cranston",
        "Pawtucket",
        "East Providence",
        "Woonsocket",
      ],
      Mississippi: [
        "Jackson",
        "Gulfport",
        "Southaven",
        "Hattiesburg",
        "Biloxi",
        "Meridian",
      ],
      "South Dakota": ["Sioux Falls", "Rapid City"],
      Connecticut: [
        "Bridgeport",
        "New Haven",
        "Stamford",
        "Hartford",
        "Waterbury",
        "Norwalk",
        "Danbury",
        "New Britain",
        "Meriden",
        "Bristol",
        "West Haven",
        "Milford",
        "Middletown",
        "Norwich",
        "Shelton",
      ],
      "South Carolina": [
        "Columbia",
        "Charleston",
        "North Charleston",
        "Mount Pleasant",
        "Rock Hill",
        "Greenville",
        "Summerville",
        "Sumter",
        "Goose Creek",
        "Hilton Head Island",
        "Florence",
        "Spartanburg",
      ],
      "New Hampshire": ["Manchester", "Nashua", "Concord"],
      "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot"],
      Montana: ["Billings", "Missoula", "Great Falls", "Bozeman"],
      Delaware: ["Wilmington", "Dover"],
      Maine: ["Portland"],
      Wyoming: ["Cheyenne", "Casper"],
      "West Virginia": ["Charleston", "Huntington"],
      Vermont: ["Burlington"],
    },
  },
};
export const dummyProducts = [
  {
    id: 1,
    name: "ROVER X Black",
    price: 1899,
  },
  {
    id: 2,
    name: "ROVER Y Black",
    price: 1999,
  },
  {
    id: 3,
    name: "Rover Bike carrier rack",
    price: 89.99,
    isFeatured: true,
    image: "/img/featured-product-1.png",
  },
  {
    id: 4,
    name: "Colored IPS Screen Display",
    price: 99.99,
    isFeatured: true,
    image: "/img/featured-product-2.png",
  },
  {
    id: 5,
    name: "Rover Bike lock",
    price: 24.99,
    isFeatured: true,
    image: "/img/featured-product-3.png",
  },
  {
    id: 6,
    name: "Rover Backpack",
    price: 149.99,
    isFeatured: true,
    image: "/img/featured-product-4.png",
  },
];
